server:
  port: 8080
  compression:
    enabled: true
    min-response-size: 10240
    mime-types: application/json,application/xml,text/plain
  forward-headers-strategy: native

spring:
  application:
    version: @project.version@
    name: dpa-id-auth0-backend-demo
  config:
    import: aws-parameterstore:/config/${spring.application.name}/
  security:
    oauth2:
      audience: VHja0nGBV6VCNJ0jh76oZ1iwLrclTOZC
      secondAudience: mKU1cZ7l3PnJtXrVOLfV9CENcp44npGR
      client:
        provider:
          dpaid-devel:
            issuer-uri: https://dpa-id-devel.eu.auth0.com/
    managementAPI:
      audience: mKU1cZ7l3PnJtXrVOLfV9CENcp44npGR
      url: https://auth-devel.dpa-id.de
      client:
        provider:
          dpaid:
            id: mKU1cZ7l3PnJtXrVOLfV9CENcp44npGR
            secret: ${CLIENT_SECRET}
            issuer-uri: https://dpa-id-devel.eu.auth0.com/api/v2/
